// <auto-generated />
namespace TSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removerequireddepartmentid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removerequireddepartmentid));
        
        string IMigrationMetadata.Id
        {
            get { return "201705220533400_remove-required-department-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
